% construct_gridded_interpolants.m
% Written by Thomas Kennings
% NASA Glenn Research Center, Cleveland, OH
% May 30, 2024

% This script pre-constructs the interpolants which are used by interpolation 
% functions. Since these functions are called repeatedly, it saves time to 
% prevent the repeated construction of interpolants.

% The pagetranspose() command will flip the 'orientation' of a 3D matrix. This means that each 
% Z-layer of the matrix will be transposed in the X-Y plane. Depending on the orientation that
% schedules were created in, it might be necessary to use the pagetranpose() command on any 3D
% matrices. If the solver is unexpectedly failing at many points, try checking whether 3D schedules
% should be page-transposed or not.

%% Variable geometry elements
VAFN_interpolant = griddedInterpolant({AGTF30_simulink_data.VAFN_mach_numbers, ...
    AGTF30_simulink_data.VAFN_N1cs}, ...
    pagetranspose(AGTF30_simulink_data.VAFN_schedule), "linear");

VBV_interpolant = griddedInterpolant({AGTF30_simulink_data.VBV_mach_numbers, ...
    AGTF30_simulink_data.VBV_N1cs}, ...
    pagetranspose(AGTF30_simulink_data.VBV_schedule), "linear");

%% Solver initial guesses
IC_interpolants.Wc = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{1}{1}, "linear");

IC_interpolants.HPT_PR = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{2}{1}, "linear");

IC_interpolants.HPC_Rline = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{3}{1}, "linear");

IC_interpolants.FAN_Rline = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{4}{1}, "linear");

IC_interpolants.BPR = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{5}{1}, "linear");

IC_interpolants.LPC_Rline = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{6}{1}, "linear");

IC_interpolants.LPT_PR = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{7}{1}, "linear");

IC_interpolants.N2 = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{8}{1}, "linear");

IC_interpolants.N3 = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{9}{1}, "linear");

IC_interpolants.Wf = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{10}{1}, "linear");

IC_interpolants.VAFN = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{11}{1}, "linear");

IC_interpolants.VBV = griddedInterpolant({AGTF30_simulink_data.command_altitudes, ...
    AGTF30_simulink_data.command_N1cs, AGTF30_simulink_data.command_mach_numbers}, ...
    AGTF30_simulink_data.command_schedules{12}{1}, "linear");
